version: '3.8'

services:
  postgres_vps:
    image: postgres
    container_name: postgres-vps
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-proxmox}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # networks:
    #   - vps_network

  # lxc_vps:
  #   image: your-lxc-image:latest
  #   container_name: lxc-vps
  #   environment:
  #     FLASK_APP: ${FLASK_APP:-app}
  #     FLASK_ENV: ${FLASK_ENV:-production}
  #     PROXMOX_USERNAME: ${PROXMOX_USERNAME:-root}
  #     PROXMOX_PASSWORD: ${PROXMOX_PASSWORD:-xcode}
  #     PROXMOX_HOST: ${PROXMOX_HOST:-postgres_vps}
  #     PROXMOX_NODE: ${PROXMOX_NODE:-pve}
  #     POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  #     POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  #     POSTGRES_DB: ${POSTGRES_DB:-proxmox}
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - vps_network
  #   depends_on:
  #     - postgres

  # nginx-automation:
  #   image: image:latest
  #   container_name: nginx-automation
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - vps_network
  
volumes:
  postgres_data:

# networks:
#   vps_network:
#     driver: bridge
