version: '3.8'

services:
<<<<<<< HEAD
  postgres_vps:
    image: postgres
    container_name: postgres-vps
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-proxmox}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
=======
  postgres-caas:
    image: postgres
    container_name: postgres-caas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proxmox
    ports:
      - "5432:5432"
>>>>>>> develop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
<<<<<<< HEAD
      - vps_network

  lxc_vps:
    image: your-lxc-image:latest
    container_name: lxc-vps
    environment:
      FLASK_APP: ${FLASK_APP:-app}
      FLASK_ENV: ${FLASK_ENV:-production}
      PROXMOX_USERNAME: ${PROXMOX_USERNAME:-root}
      PROXMOX_PASSWORD: ${PROXMOX_PASSWORD:-xcode}
      PROXMOX_HOST: ${PROXMOX_HOST:-postgres_vps}
      PROXMOX_NODE: ${PROXMOX_NODE:-pve}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-proxmox}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "${HOST_PORT:-3000}:80"
    networks:
      - vps_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  vps_network:
    driver: bridge
=======
      - caas_networks

  lxc-manager:
    image: dzakimaulanaasif/lxc-manager:latest
    container_name: lxc-manager
    environment:
      FLASK_APP: app
      FLASK_ENV: production
      PROXMOX_USERNAME: root@pam
      PROXMOX_PASSWORD: xcode2024
      PROXMOX_HOST: 192.168.40.2
      PROXMOX_NODE: xcode
      POSTGRES_HOST: postgres-caas
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
      POSTGRES_DB: proxmox
      DEPLOY_AUTOMATION_URL: http://deploy-automation:5000
      CONTAINER_IP_RANGE: 192.168.40.0/24
      CONTAINER_GATEWAY: 192.168.40.1
    ports:
      - "3000:3000"
    command: ["python", "run.py"]
    networks:
      - caas_networks
    depends_on:
      - postgres-caas

  deploy-automation:
    image: dzakimaulanaasif/deploy-automation:latest
    container_name: deploy-automation
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      API_KEY: NxIpYuEoQdIhYD4bdq2QI6x0FQHvtuVt3INdmyAy
      ZONE_ID: 53a1bb5ac41d5eab5bab1e4f8c4b9ef0
      IP_PUBLIC: 103.174.114.68
      ROOT_SERVER_NAME: wehos.online
    volumes:
      - /usr/bin:/usr/bin
      - /home/xcode/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /etc/nginx/sites-available:/etc/nginx/sites-available:rw
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    command: ["python", "run.py"]
    networks:
      - caas_networks
    depends_on:
      - lxc-manager
  
  fe-caas:
    image: lutpann/fe-caas:2.4
    container_name: fe-caas
    environment:
      DATABASE_URL: postgres-caas
    ports:
      - "8080:8080"
    networks:
      - caas_networks

volumes:
  postgres_data:
    name: postgres_data

networks:
  caas_networks:
    name: caas_networks
    driver: bridge
>>>>>>> develop
