from app import cur
from config import Config
from datetime import datetime
class LXCDB:
    def __init__(self, vmid=0, hostname='', password='', ip_addr='', ostemplate='', lxc_type=''):
        self.id = None  # ID will be automatically generated by the database
        self.vmid = vmid
        self.hostname = hostname
        self.password = password
        self.ip_addr = ip_addr
        self.ostemplate = ostemplate
        self.lxc_type = lxc_type
        self.created = datetime.now()
        self.updated = datetime.now()

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "vmid": self.vmid,
            "hostname": self.hostname,
            "password": self.password,
            "ip_addr": self.ip_addr,
            "ostemplate" : self.ostemplate,
            "lxc_type": self.lxc_type,
            "created": self.created,
            "updated": self.updated
        }

    def add_lxc(self):
        try:
            ADD_LXC_QUERY = (
                """INSERT INTO proxmox (created, updated, vmid, hostname, password, ipv4, ostemplate, lxc_type)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id;"""
            )
            cur.execute(ADD_LXC_QUERY, (self.created, self.updated, self.vmid, self.hostname, self.password, self.ip_addr, self.ostemplate, self.lxc_type))
            self.id = cur.fetchone()[0]
            Config.conn.commit()
            return (True, None)
        except Exception as e:
            Config.conn.rollback()
            return (False, f"[!] Error add LXC data: {e}")
    
    @staticmethod
    def initialize_table():
        try:
            CREATE_PROXMOX_TABLE = (
                """CREATE TABLE IF NOT EXISTS lxc (
                    id SERIAL PRIMARY KEY,
                    created TIMESTAMP,
                    updated TIMESTAMP,
                    vmid INTEGER,
                    hostname VARCHAR(255),
                    password VARCHAR(255),
                    ipv4 VARCHAR(255),
                    ostemplate VARCHAR(255),
                    lxc_type VARCHAR(255)
                );"""
            )
            cur.execute(CREATE_PROXMOX_TABLE)
            Config.conn.commit()
            return (True, None)
        except Exception as e:
            Config.conn.rollback()
            return (False, f"[!] Error initialize table: {e}")

    @staticmethod
    def get_all_lxc():
        try:
            GET_ALL_LXC_QUERRY = (
                """SELECT * FROM proxmox;"""
            )
            cur.execute(GET_ALL_LXC_QUERRY)
            rows = cur.fetchall()
            columns = ['id', 'created', 'updated', 'vmid', 'hostname', 'password', 'ipv4', 'ostemplate', 'lxc_type']
            data = [dict(zip(columns, row)) for row in rows]
            return (True, data)
        except Exception as e:
            return (False, f"[!] Error get all LXC data: {e}")


    @staticmethod
    def delete_lxc(id):
        try:
            DELETE_LXC_QUERY = (
                """DELETE FROM proxmox WHERE id = %s;"""
            )
            cur.execute(DELETE_LXC_QUERY, (id,))
            Config.conn.commit()
            return (True, None)
        except Exception as e:
            Config.conn.rollback()
            return (False, f"[!] Error delete LXC: {e}")
    
    @staticmethod
    def get_all_vmid():
        try:
            ALL_VMID_LXC = (
                """SELECT vmid FROM proxmox;"""
            )
            cur.execute(ALL_VMID_LXC)
            vmid_data = cur.fetchall()
            vmid_list = [row[0] for row in vmid_data]
            return (True, vmid_list)
        except Exception as e:
            return (False, f"[!] Error get all vmid LXC: {e}")
